language: php
php:
    - 7.2
    - nightly
matrix:
  allow_failures:
  - php: nightly
before_script: composer install
script:
  - bin/phpunit --coverage-clover=coverage.clover
  - if [ "$TRAVIS_PHP_VERSION" != "nightly" ]; then bin/infection -s --only-covered --min-msi=100; fi
after_script:
    - if [ "$TRAVIS_PHP_VERSION" = "7.1" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
    - if [ "$TRAVIS_PHP_VERSION" = "7.1" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
notifications:
    slack: innmind:nAiLaAi6RU4wGEAdL6FuKdyF
