application:
    build: docker/code
    volumes:
        - .:/var/www/symfony
        - ./app/logs:/var/www/symfony/app/logs
    tty: true
db:
    image: tpires/neo4j
    ports:
        - 7474:7474
    environment:
        NEO4J_AUTH: neo4j:docker
php:
    build: docker/php-fpm
    expose:
        - 9000:9000
    volumes_from:
        - application
    links:
        - db
nginx:
    build: docker/nginx
    ports:
        - 80:80
    links:
        - php
    volumes_from:
        - application
    volumes:
        - ./app/logs:/var/log/nginx
