version: '2'
services:
    web:
        build: .
        volumes:
            - .:/var/www/html
        ports:
            - '8080:80'
        links:
            - neo4j

    neo4j:
        image: neo4j:3.1
        ports:
            - '7474:7474'
