innmind_rest:
    server:
        collections:
            web:
                storage: neo4j
                resources:
                    resource:
                        id: uuid
                        properties:
                            uuid: string
                            domain:
                                type: string
                                access: [READ, CREATE]
                            tld:
                                type: string
                                access: [READ, CREATE]
                            host:
                                type: string
                                access: [READ, CREATE]
                            scheme:
                                type: string
                                access: [READ, CREATE]
                            port:
                                type: int
                                access: [READ, CREATE]
                            path:
                                type: string
                                access: [READ, CREATE]
                            query:
                                type: string
                                access: [READ, CREATE]
                            charset:
                                type: string
                                access: [READ, CREATE]
                                options:
                                    optional: true
                            alternates:
                                type: array
                                access: [READ, CREATE]
                                options:
                                    inner_type: resource
                                    resource: alternate
                                    optional: true
                            canonical:
                                type: string
                                access: [READ, CREATE]
                                options:
                                    optional: true
                        options:
                            class: APIBundle\Graph\Node\HttpResource
                        meta:
                            accept:
                                type: '*'
                                quality: 0.1
                    html:
                        id: uuid
                        properties:
                            uuid: string
                            domain:
                                type: string
                                access: [READ, CREATE]
                            tld:
                                type: string
                                access: [READ, CREATE]
                            host:
                                type: string
                                access: [READ, CREATE]
                            scheme:
                                type: string
                                access: [READ, CREATE]
                            port:
                                type: int
                                access: [READ, CREATE]
                            path:
                                type: string
                                access: [READ, CREATE]
                            query:
                                type: string
                                access: [READ, CREATE]
                            charset:
                                type: string
                                access: [READ, CREATE]
                                options:
                                    optional: true
                            alternates:
                                type: array
                                access: [READ, CREATE]
                                options:
                                    inner_type: resource
                                    resource: alternate
                                    optional: true
                            canonical:
                                type: string
                                access: [READ, CREATE]
                                options:
                                    optional: true
                            content:
                                type: string
                                access: [READ, CREATE]
                            description:
                                type: string
                                access: [READ, CREATE]
                            anchors:
                                type: array
                                access: [READ, CREATE]
                                options:
                                    inner_type: string
                            journal:
                                type: bool
                                access: [READ, CREATE]
                                options:
                                    optional: true
                            language:
                                type: string
                                access: [READ, CREATE]
                                options:
                                    optional: true
                            theme_color:
                                type: array
                                access: [READ, CREATE]
                                options:
                                    inner_type: float
                                    optional: true
                            title:
                                type: string
                                access: [READ, CREATE]
                            rss:
                                type: string
                                access: [READ, CREATE]
                                options:
                                    optional: true
                            android:
                                type: string
                                access: [READ, CREATE]
                                options:
                                    optional: true
                            ios:
                                type: string
                                access: [READ, CREATE]
                                options:
                                    optional: true
                            images:
                                type: array
                                access: [READ, CREATE]
                                options:
                                    inner_type: resource
                                    resource: image_caption
                                    optional: true
                            links:
                                type: array
                                access: [READ, CREATE]
                                options:
                                    inner_type: string
                                    optional: true
                            author:
                                type: string
                                access: [READ, CREATE]
                                options:
                                    optional: true
                            citations:
                                type: array
                                access: [READ, CREATE]
                                options:
                                    inner_type: string
                                    optional: true
                        options:
                            class: APIBundle\Graph\Node\Html
                        meta:
                            accept:
                                type: '*html*'
                                quality: 1
                    image:
                        id: uuid
                        properties:
                            uuid: string
                            domain:
                                type: string
                                access: [READ, CREATE]
                            tld:
                                type: string
                                access: [READ, CREATE]
                            host:
                                type: string
                                access: [READ, CREATE]
                            scheme:
                                type: string
                                access: [READ, CREATE]
                            port:
                                type: int
                                access: [READ, CREATE]
                            path:
                                type: string
                                access: [READ, CREATE]
                            query:
                                type: string
                                access: [READ, CREATE]
                            charset:
                                type: string
                                access: [READ, CREATE]
                                options:
                                    optional: true
                            alternates:
                                type: array
                                access: [READ, CREATE]
                                options:
                                    inner_type: resource
                                    resource: alternate
                                    optional: true
                            canonical:
                                type: string
                                access: [READ, CREATE]
                                options:
                                    optional: true
                            width:
                                type: int
                                access: [READ, CREATE]
                            height:
                                type: int
                                access: [READ, CREATE]
                            mime:
                                type: string
                                access: [READ, CREATE]
                            extension:
                                type: string
                                access: [READ, CREATE]
                            weight:
                                type: int
                                access: [READ, CREATE]
                            exif:
                                type: string
                                access: [READ, CREATE]
                                options:
                                    optional: true
                        options:
                            class: APIBundle\Graph\Node\Image
                        meta:
                            accept:
                                type: 'image/*'
                                quality: 1
                    image_caption:
                        id: url
                        properties:
                            url:
                                type: string
                                access: [READ, CREATE]
                            description:
                                type: string
                                access: [READ, CREATE]
                        options:
                            private: true
                    alternate:
                        id: url
                        properties:
                            url:
                                type: string
                                access: [READ, CREATE]
                            language:
                                type: string
                                access: [READ, CREATE]
                        options:
                            private: true
