imports:
    - { resource: services/repositories.yml }
    - { resource: services/identity_generators.yml }
    - { resource: services/handlers.yml }
    - { resource: services/gateways.yml }
    - { resource: services/listeners.yml }

services:
    command_bus: '@innmind_command_bus'

    command_bus.persister:
        class: AppBundle\CommandBus\PersisterCommandBus
        arguments:
            - ~
            - '@innmind_neo4j.manager'
        tags:
            - { name: innmind_command_bus, alias: persister }
