imports:
    - { resource: services/repositories.yml }
    - { resource: services/identity_generators.yml }
    - { resource: services/handlers.yml }
    - { resource: services/gateways.yml }
    - { resource: services/listeners.yml }
    - { resource: services/onm.yml }

services:
    command_bus: '@innmind_command_bus'

    command_bus.persister:
        class: AppBundle\CommandBus\PersisterCommandBus
        arguments:
            - ~
            - '@innmind_neo4j.manager'
        tags:
            - { name: innmind_command_bus, alias: persister }

    domain_parser:
        class: Pdp\Parser
        factory:
            - AppBundle\Factory\DomainParserFactory
            - make

    clock:
        class: Innmind\TimeContinuum\TimeContinuum\Earth
        arguments:
            - '@clock.timezone.paris'

    clock.timezone.paris:
        class: Innmind\TimeContinuum\Timezone\Earth\Europe\Paris
        public: false
