APIBundle\Graph\Relationship\Alternate:
    type: relationship
    alias: Alternate
    id:
        uuid:
            type: string
            generator: { strategy: UUID }
    rel_type: ALTERNATE_OF
    properties:
        source:
            type: startNode
            node: Resource
        destination:
            type: endNode
            node: Resource
        date: date
        language: string
