APIBundle\Graph\Node\Author:
    type: node
    alias: Author
    id:
        uuid:
            type: string
            generator: { strategy: UUID }
    labels: [Author]
    properties:
        name: string
