APIBundle\Graph\Relationship\Canonical:
    type: relationship
    alias: Canonical
    id:
        uuid:
            type: string
            generator: { strategy: UUID }
    rel_type: CANONICAL_OF
    properties:
        source:
            type: startNode
            node: Resource
        destination:
            type: endNode
            node: Resource
