APIBundle\Graph\Relationship\CitedIn:
    type: relationship
    alias: CitedIn
    id:
        uuid:
            type: string
            generator: { strategy: UUID }
    rel_type: CITED_IN
    properties:
        citation:
            type: startNode
            node: Citation
        resource:
            type: endNode
            node: Resource
        date: date
