APIBundle\Graph\Relationship\HostOfDomain:
    type: relationship
    alias: HostOfDomain
    id:
        uuid:
            type: string
            generator: { strategy: UUID }
    rel_type: HOST_OF_DOMAIN
    properties:
        host:
            type: startNode
            node: Host
        domain:
            type: endNode
            node: Domain
