APIBundle\Graph\Node\Image:
    type: node
    alias: Image
    id:
        uuid:
            type: string
            generator: { strategy: UUID }
    labels: [Resource, Image]
    properties:
        scheme: string
        port: int
        path: string
        query: string
        charset: string
        width: int
        height: int
        mime: string
        extension: string
        weight: int
        exif: json
