APIBundle\Graph\Relationship\PageAuthor:
    type: relationship
    alias: PageAuthor
    id:
        uuid:
            type: string
            generator: { strategy: UUID }
    rel_type: AUTHOR_OF_PAGE
    properties:
        author:
            type: startNode
            node: Author
        page:
            type: endNode
            node: Html
        date: date
