APIBundle\Graph\Relationship\PageImage:
    type: relationship
    alias: PageImage
    id:
        uuid:
            type: string
            generator: { strategy: UUID }
    rel_type: IMAGE_OF_PAGE
    properties:
        image:
            type: startNode
            node: Image
        page:
            type: endNode
            node: Html
        date: date
        description: string
