APIBundle\Graph\Relationship\ResourceOfHost:
    type: relationship
    alias: ResourceOfHost
    id:
        uuid:
            type: string
            generator: { strategy: UUID }
    rel_type: RESOURCE_OF_HOST
    properties:
        resource:
            type: startNode
            node: Resource
        host:
            type: endNode
            node: Host
        date: date
