services:
    entity_factory.alternates:
        class: APIBundle\EntityFactory\AlternatesFactory
        arguments:
            - '@event_dispatcher'

    entity_factory.author:
        class: APIBundle\EntityFactory\AuthorFactory
        arguments:
            - '@event_dispatcher'

    entity_factory.canonical:
        class: APIBundle\EntityFactory\CanonicalFactory
        arguments:
            - '@event_dispatcher'

    entity_factory.citations:
        class: APIBundle\EntityFactory\CitationsFactory
        arguments:
            - '@event_dispatcher'

    entity_factory.domain:
        class: APIBundle\EntityFactory\DomainFactory
        arguments:
            - '@event_dispatcher'

    entity_factory.host:
        class: APIBundle\EntityFactory\HostFactory
        arguments:
            - '@event_dispatcher'
            - '@entity_factory.domain'

    entity_factory.html:
        class: APIBundle\EntityFactory\HtmlFactory
        arguments:
            - '@entity_factory.resource'
            - '@entity_factory.images'
            - '@entity_factory.links'
            - '@entity_factory.author'
            - '@entity_factory.citations'

    entity_factory.resource:
        class: APIBundle\EntityFactory\HttpResourceFactory
        arguments:
            - '@entity_factory.host'
            - '@entity_factory.alternates'
            - '@entity_factory.canonical'

    entity_factory.image:
        class: APIBundle\EntityFactory\ImageFactory
        arguments:
            - '@entity_factory.resource'

    entity_factory.images:
        class: APIBundle\EntityFactory\ImagesFactory
        arguments:
            - '@event_dispatcher'

    entity_factory.links:
        class: APIBundle\EntityFactory\LinksFactory
        arguments:
            - '@event_dispatcher'

    entity_factory.delegation:
        class: APIBundle\EntityFactory\DelegationFactory
        arguments:
            -
                - '@entity_factory.resource'
                - '@entity_factory.html'
                - '@entity_factory.image'
