services:
    listener.entity_builder:
        class: APIBundle\EventListener\EntityBuilderListener
        arguments:
            - '@entity_factory.delegation'
            - '@resource_factory.delegation'
        tags:
            - { name: kernel.event_subscriber }

    listener.relationship_persist:
        class: APIBundle\EventListener\RelationshipPersistListener
        arguments:
            - '@innmind_neo4j.manager.default'
        tags:
            - { name: kernel.event_subscriber }

    listener.build.targetable:
        class: APIBundle\EventListener\TargetableBuildListener
        arguments:
            - '@innmind_neo4j.manager.default'
            - '@domain_parser'
        tags:
            - { name: kernel.event_subscriber }

    listener.build.author:
        class: APIBundle\EventListener\AuthorBuildListener
        arguments:
            - '@innmind_neo4j.manager.default'
        tags:
            - { name: kernel.event_subscriber }

    listener.build.citation:
        class: APIBundle\EventListener\CitationBuildListener
        arguments:
            - '@innmind_neo4j.manager.default'
        tags:
            - { name: kernel.event_subscriber }

    listener.build.domain:
        class: APIBundle\EventListener\DomainBuildListener
        arguments:
            - '@innmind_neo4j.manager.default'
        tags:
            - { name: kernel.event_subscriber }

    listener.build.host:
        class: APIBundle\EventListener\HostBuildListener
        arguments:
            - '@innmind_neo4j.manager.default'
        tags:
            - { name: kernel.event_subscriber }

    listener.crawl:
        class: APIBundle\EventListener\CrawlListener
        arguments:
            - '@old_sound_rabbit_mq.crawling_producer'
        tags:
            - { name: kernel.event_subscriber }

    listener.mutation:
        class: APIBundle\EventListener\MutationListener
        arguments:
            - '@innmind_neo4j.manager.default'
        tags:
            - { name: kernel.event_subscriber }
