services:
    listener.entity_builder:
        class: APIBundle\EventListener\EntityBuilderListener
        arguments:
            - @entity_factory.delegation
        tags:
            - { name: kernel.event_subscriber }

    listener.relationship_persist:
        class: APIBundle\EventListener\RelationshipPersistListener
        arguments:
            - @innmind_neo4j.manager.default
        tags:
            - { name: kernel.event_subscriber }

    listener.build.alternate:
        class: APIBundle\EventListener\AlternateBuildListener
        arguments:
            - @innmind_neo4j.manager.default
            - @domain_parser
        tags:
            - { name: kernel.event_subscriber }

    listener.build.canonical:
        class: APIBundle\EventListener\CanonicalBuildListener
        arguments:
            - @innmind_neo4j.manager.default
            - @domain_parser
        tags:
            - { name: kernel.event_subscriber }

    listener.build.author:
        class: APIBundle\EventListener\AuthorBuildListener
        arguments:
            - @innmind_neo4j.manager.default
        tags:
            - { name: kernel.event_subscriber }
