imports:
    - { resource: entity_factories.yml }
    - { resource: resource_factories.yml }
    - { resource: listeners.yml }

services:
    neo4j_storage:
        parent: innmind_rest.server.storage.abstract.neo4j
        arguments:
            index_0: '@innmind_neo4j.manager.default'
        tags:
            - { name: innmind_rest.server.storage, alias: neo4j }

    domain_parser:
        class: Pdp\Parser
        arguments:
            - @=service('domain_parser.suffix').getList()

    domain_parser.suffix:
        class: Pdp\PublicSuffixListManager

    serializer:
        class: Symfony\Component\Serializer\Serializer
        arguments:
            - []
            - []
