arguments:
    entities: array
    logger: Psr\Log\LoggerInterface
    domainEventsStorage: string # filesystem path

dependencies:
    commandBus @innmind/command-bus/container.yml:
        handlers: $handlers
        logger: $logger

    eventBus @innmind/event-bus/container.yml:
        listeners: $listeners

    transport @innmind/http-transport/container.yml: []

    dbal @innmind/neo4j-dbal/container.yml:
        transport: $transport.conservative
        clock: $clock

    orm @innmind/neo4j-onm/container.yml:
        connection: $dbal.connection
        metas: $entities
        eventBus: $appEventBus
        additionalTypes: $db.types
        additionalGenerators: $db.generators
        extractionStrategy: $db.extractionStrategy

expose:
    httpResource: $gateway.httpResource
    image: $gateway.image
    htmlPage: $gateway.htmlPage

services:
    appEventBus stack:
        - $eventBus.queue
        - $eventBus.bus

    appCommandBus stack:
        - $commandBus.queue
        - $commandBus.logger
        - $commandBus.clearDomainEvents
        - $commandBus.dispatchDomainEvents
        - $commandBus.persister
        - $commandBus.bus

    commandBus:
        persister AppBundle\CommandBus\PersisterBus:
            - '@decorated'
            - $orm.manager

        dispatchDomainEvents AppBundle\CommandBus\DispatchDomainEventsBus:
            - '@decorated'
            - $appEventBus
            - $orm.container

        clearDomainEvents AppBundle\CommandBus\ClearDomainEventsBus:
            - '@decorated'
            - $orm.container

    gateway:
        httpResource AppBundle\Rest\Gateway\HttpResourceGateway:
            - $gateway.httpResource.creator
            - $gateway.httpResource.accessor
            - $gateway.httpResource.linker

        httpResource:
            creator AppBundle\Rest\Gateway\HttpResourceGateway\ResourceCreator:
                - $appCommandBus
            accessor AppBundle\Rest\Gateway\HttpResourceGateway\ResourceAccessor:
                - $repository.httpResource
                - $dbal.connection
            linker AppBundle\Rest\Gateway\HttpResourceGateway\ResourceLinker:
                - $appCommandBus

        image AppBundle\Rest\Gateway\ImageGateway:
            - $gateway.image.creator
            - $gateway.image.accessor

        image:
            creator AppBundle\Rest\Gateway\ImageGateway\ResourceCreator:
                - $appCommandBus
            accessor AppBundle\Rest\Gateway\ImageGateway\ResourceAccessor:
                - $repository.image
                - $dbal.connection

        htmlPage AppBundle\Rest\Gateway\HtmlPageGateway:
            - $gateway.htmlPage.creator
            - $gateway.htmlPage.accessor
            - $gateway.htmlPage.linker

        htmlPage:
            creator AppBundle\Rest\Gateway\HtmlPageGateway\ResourceCreator:
                - $appCommandBus
            accessor AppBundle\Rest\Gateway\HtmlPageGateway\ResourceAccessor:
                - $repository.htmlPage
                - $dbal.connection
            linker AppBundle\Rest\Gateway\HtmlPageGateway\ResourceLinker:
                - $appCommandBus

    repository:
        author AppBundle\Repository\Neo4j\AuthorRepository:
            - $repository.neo4j.author
        resourceAuthor AppBundle\Repository\Neo4j\ResourceAuthorRepository:
            - $repository.neo4j.resourceAuthor
        citation AppBundle\Repository\Neo4j\CitationRepository:
            - $repository.neo4j.citation
        citationAppearance AppBundle\Repository\Neo4j\CitationAppearanceRepository:
            - $repository.neo4j.citationAppearance
        domain AppBundle\Repository\Neo4j\DomainRepository:
            - $repository.neo4j.domain
        domainHost AppBundle\Repository\Neo4j\DomainHostRepository:
            - $repository.neo4j.domainHost
        host AppBundle\Repository\Neo4j\HostRepository:
            - $repository.neo4j.host
        hostResource AppBundle\Repository\Neo4j\HostResourceRepository:
            - $repository.neo4j.hostResource
        httpResource AppBundle\Repository\Neo4j\HttpResourceRepository:
            - $repository.neo4j.httpResource
        image AppBundle\Repository\Neo4j\ImageRepository:
            - $repository.neo4j.image
        htmlPage AppBundle\Repository\Neo4j\HtmlPageRepository:
            - $repository.neo4j.htmlPage
        alternate AppBundle\Repository\Neo4j\AlternateRepository:
            - $repository.neo4j.alternate
        canonical AppBundle\Repository\Neo4j\CanonicalRepository:
            - $repository.neo4j.canonical
        reference AppBundle\Repository\Neo4j\ReferenceRepository:
            - $repository.neo4j.reference

        neo4j:
            author AppBundle\Factory\Repository::build:
                - $orm.manager
                - Domain\Entity\Author
            resourceAuthor AppBundle\Factory\Repository::build:
                - $orm.manager
                - Domain\Entity\ResourceAuthor
            citation AppBundle\Factory\Repository::build:
                - $orm.manager
                - Domain\Entity\Citation
            citationAppearance AppBundle\Factory\Repository::build:
                - $orm.manager
                - Domain\Entity\CitationAppearance
            domain AppBundle\Factory\Repository::build:
                - $orm.manager
                - Domain\Entity\Domain
            domainHost AppBundle\Factory\Repository::build:
                - $orm.manager
                - Domain\Entity\DomainHost
            host AppBundle\Factory\Repository::build:
                - $orm.manager
                - Domain\Entity\Host
            hostResource AppBundle\Factory\Repository::build:
                - $orm.manager
                - Domain\Entity\HostResource
            httpResource AppBundle\Factory\Repository::build:
                - $orm.manager
                - Domain\Entity\HttpResource
            image AppBundle\Factory\Repository::build:
                - $orm.manager
                - Domain\Entity\Image
            htmlPage AppBundle\Factory\Repository::build:
                - $orm.manager
                - Domain\Entity\HtmlPage
            alternate AppBundle\Factory\Repository::build:
                - $orm.manager
                - Domain\Entity\Alternate
            canonical AppBundle\Factory\Repository::build:
                - $orm.manager
                - Domain\Entity\Canonical
            reference AppBundle\Factory\Repository::build:
                - $orm.manager
                - Domain\Entity\Reference

    handlers map<string, callable>:
        - <Domain\Command\RegisterAuthor, $handler.registerAuthor>
        - <Domain\Command\RegisterCitation, $handler.registerCitation>
        - <Domain\Command\Citation\RegisterAppearance, $handler.registerCitationAppearance>
        - <Domain\Command\RegisterDomain, $handler.registerDomain>
        - <Domain\Command\RegisterHost, $handler.registerHost>
        - <Domain\Command\RegisterHttpResource, $handler.registerHttpResource>
        - <Domain\Command\HttpResource\SpecifyCharset, $handler.httpResource.specifyCharset>
        - <Domain\Command\HttpResource\SpecifyLanguages, $handler.httpResource.specifyLanguages>
        - <Domain\Command\HttpResource\RegisterAuthor, $handler.httpResource.registerAuthor>
        - <Domain\Command\RegisterImage, $handler.registerImage>
        - <Domain\Command\Image\SpecifyDimension, $handler.image.specifyDimension>
        - <Domain\Command\Image\SpecifyWeight, $handler.image.specifyWeight>
        - <Domain\Command\Image\AddDescription, $handler.image.addDescription>
        - <Domain\Command\RegisterHtmlPage, $handler.registerHtmlPage>
        - <Domain\Command\HtmlPage\FlagAsJournal, $handler.htmlPage.flagAsJournal>
        - <Domain\Command\HtmlPage\SpecifyAnchors, $handler.htmlPage.specifyAnchors>
        - <Domain\Command\HtmlPage\SpecifyAndroidAppLink, $handler.htmlPage.specifyAndroidAppLink>
        - <Domain\Command\HtmlPage\SpecifyIosAppLink, $handler.htmlPage.specifyIosAppLink>
        - <Domain\Command\HtmlPage\SpecifyPreview, $handler.htmlPage.specifyPagePreview>
        - <Domain\Command\HtmlPage\SpecifyDescription, $handler.htmlPage.specifyDescription>
        - <Domain\Command\HtmlPage\SpecifyMainContent, $handler.htmlPage.specifyMainContent>
        - <Domain\Command\HtmlPage\SpecifyThemeColour, $handler.htmlPage.specifyThemeColour>
        - <Domain\Command\HtmlPage\SpecifyTitle, $handler.htmlPage.specifyTitle>
        - <Domain\Command\RegisterAlternateResource, $handler.htmlPage.registerAlternate>
        - <Domain\Command\MakeCanonicalLink, $handler.htmlPage.makeCanonicalLink>
        - <Domain\Command\ReferResource, $handler.htmlPage.refer>

    handler:
        registerAuthor Domain\Handler\RegisterAuthorHandler:
            - $repository.author
        registerCitation Domain\Handler\RegisterCitationHandler:
            - $repository.citation
        registerCitationAppearance Domain\Handler\Citation\RegisterAppearanceHandler:
            - $repository.citationAppearance
            - $clock
        registerDomain Domain\Handler\RegisterDomainHandler:
            - $repository.domain
            - $domainParser
        registerHost Domain\Handler\RegisterHostHandler:
            - $repository.host
            - $repository.domainHost
            - $clock
        registerHttpResource Domain\Handler\RegisterHttpResourceHandler:
            - $repository.httpResource
            - $repository.hostResource
            - $clock
        httpResource:
            specifyCharset Domain\Handler\HttpResource\SpecifyCharsetHandler:
                - $repository.httpResource
            specifyLanguages Domain\Handler\HttpResource\SpecifyLanguagesHandler:
                - $repository.httpResource
            registerAuthor Domain\Handler\HttpResource\RegisterAuthorHandler:
                - $repository.resourceAuthor
                - $clock
        registerImage Domain\Handler\RegisterImageHandler:
            - $repository.image
            - $repository.hostResource
            - $clock
        image:
            specifyDimension Domain\Handler\Image\SpecifyDimensionHandler:
                - $repository.image
            specifyWeight Domain\Handler\Image\SpecifyWeightHandler:
                - $repository.image
            addDescription Domain\Handler\Image\AddDescriptionHandler:
                - $repository.image
        registerHtmlPage Domain\Handler\RegisterHtmlPageHandler:
            - $repository.htmlPage
            - $repository.hostResource
            - $clock
        htmlPage:
            flagAsJournal Domain\Handler\HtmlPage\FlagAsJournalHandler:
                - $repository.htmlPage
            specifyAnchors Domain\Handler\HtmlPage\SpecifyAnchorsHandler:
                - $repository.htmlPage
            specifyAndroidAppLink Domain\Handler\HtmlPage\SpecifyAndroidAppLinkHandler:
                - $repository.htmlPage
            specifyIosAppLink Domain\Handler\HtmlPage\SpecifyIosAppLinkHandler:
                - $repository.htmlPage
            specifyPagePreview Domain\Handler\HtmlPage\SpecifyPreviewHandler:
                - $repository.htmlPage
            specifyDescription Domain\Handler\HtmlPage\SpecifyDescriptionHandler:
                - $repository.htmlPage
            specifyMainContent Domain\Handler\HtmlPage\SpecifyMainContentHandler:
                - $repository.htmlPage
            specifyThemeColour Domain\Handler\HtmlPage\SpecifyThemeColourHandler:
                - $repository.htmlPage
            specifyTitle Domain\Handler\HtmlPage\SpecifyTitleHandler:
                - $repository.htmlPage
            registerAlternate Domain\Handler\RegisterAlternateResourceHandler:
                - $repository.alternate
            makeCanonicalLink Domain\Handler\MakeCanonicalLinkHandler:
                - $repository.canonical
                - $clock
            refer Domain\Handler\ReferResourceHandler:
                - $repository.reference

    listeners map<string, Innmind\Immutable\SetInterface>:
        - <Domain\Event\*, $listeners.domainEvents>
    listeners:
        domainEvents set<callable>:
            - $listener.storeDomainEvents

    listener:
        storeDomainEvents AppBundle\Listener\StoreDomainEventListener:
            - $innmindFilesystem

    db:
        generators map<string, Innmind\Neo4j\ONM\Identity\Generator>:
            - <AppBundle\Entity\Author\Identity, $db.generator.author>
            - <AppBundle\Entity\ResourceAuthor\Identity, $db.generator.resourceAuthor>
            - <AppBundle\Entity\Citation\Identity, $db.generator.citation>
            - <AppBundle\Entity\CitationAppearance\Identity, $db.generator.citationAppearance>
            - <AppBundle\Entity\Domain\Identity, $db.generator.domain>
            - <AppBundle\Entity\DomainHost\Identity, $db.generator.domainHost>
            - <AppBundle\Entity\Host\Identity, $db.generator.host>
            - <AppBundle\Entity\HostResource\Identity, $db.generator.hostResource>
            - <AppBundle\Entity\HttpResource\Identity, $db.generator.httpResource>
            - <AppBundle\Entity\Image\Identity, $db.generator.image>
            - <AppBundle\Entity\HtmlPage\Identity, $db.generator.htmlPage>
            - <AppBundle\Entity\Alternate\Identity, $db.generator.alternate>
            - <AppBundle\Entity\Canonical\Identity, $db.generator.canonical>
            - <AppBundle\Entity\Reference\Identity, $db.generator.reference>

        generator:
            author Innmind\Neo4j\ONM\Identity\Generator\UuidGenerator:
                - AppBundle\Entity\Author\Identity
            resourceAuthor Innmind\Neo4j\ONM\Identity\Generator\UuidGenerator:
                - AppBundle\Entity\ResourceAuthor\Identity
            citation Innmind\Neo4j\ONM\Identity\Generator\UuidGenerator:
                - AppBundle\Entity\Citation\Identity
            citationAppearance Innmind\Neo4j\ONM\Identity\Generator\UuidGenerator:
                - AppBundle\Entity\CitationAppearance\Identity
            domain Innmind\Neo4j\ONM\Identity\Generator\UuidGenerator:
                - AppBundle\Entity\Domain\Identity
            domainHost Innmind\Neo4j\ONM\Identity\Generator\UuidGenerator:
                - AppBundle\Entity\DomainHost\Identity
            host Innmind\Neo4j\ONM\Identity\Generator\UuidGenerator:
                - AppBundle\Entity\Host\Identity
            hostResource Innmind\Neo4j\ONM\Identity\Generator\UuidGenerator:
                - AppBundle\Entity\HostResource\Identity
            httpResource Innmind\Neo4j\ONM\Identity\Generator\UuidGenerator:
                - AppBundle\Entity\HttpResource\Identity
            image Innmind\Neo4j\ONM\Identity\Generator\UuidGenerator:
                - AppBundle\Entity\Image\Identity
            htmlPage Innmind\Neo4j\ONM\Identity\Generator\UuidGenerator:
                - AppBundle\Entity\HtmlPage\Identity
            alternate Innmind\Neo4j\ONM\Identity\Generator\UuidGenerator:
                - AppBundle\Entity\Alternate\Identity
            canonical Innmind\Neo4j\ONM\Identity\Generator\UuidGenerator:
                - AppBundle\Entity\Canonical\Identity
            reference Innmind\Neo4j\ONM\Identity\Generator\UuidGenerator:
                - AppBundle\Entity\Reference\Identity

        types set<string>:
            - AppBundle\Neo4j\Type\Author\NameType
            - AppBundle\Neo4j\Type\Citation\TextType
            - AppBundle\Neo4j\Type\Domain\NameType
            - AppBundle\Neo4j\Type\Domain\TopLevelDomainType
            - AppBundle\Neo4j\Type\Host\NameType
            - AppBundle\Neo4j\Type\HttpResource\CharsetType
            - AppBundle\Neo4j\Type\HttpResource\PathType
            - AppBundle\Neo4j\Type\HttpResource\QueryType
            - AppBundle\Neo4j\Type\LanguageType
            - AppBundle\Neo4j\Type\Image\DescriptionType
            - AppBundle\Neo4j\Type\Image\DimensionType
            - AppBundle\Neo4j\Type\Image\WeightType
            - AppBundle\Neo4j\Type\HtmlPage\AnchorType
            - AppBundle\Neo4j\Type\UrlType
            - AppBundle\Neo4j\Type\ColourType
            - Innmind\Neo4j\ONM\Type\PointInTimeType

        extractionStrategy Innmind\Reflection\ExtractionStrategy\ReflectionStrategy: []

    domainParser AppBundle\Factory\DomainParserFactory::make: []

    innmindFilesystem Innmind\Filesystem\Adapter\FilesystemAdapter:
        - $domainEventsStorage

    clock Innmind\TimeContinuum\TimeContinuum\Earth:
        - $clock.timezone

    clock:
        timezone Innmind\TimeContinuum\Timezone\Earth\UTC: []
