Domain\Entity\HtmlPage:
    type: aggregate
    labels: [Web, Resource, Html]
    identity:
        property: identity
        type: AppBundle\Entity\HtmlPage\Identity
    properties:
        path:
            type: http_resource_path
        query:
            type: http_resource_query
        languages:
            type: set
            inner: language
            set_type: Domain\Model\Language
        charset:
            type: http_resource_charset
        mainContent:
            type: string
        description:
            type: string
        anchors:
            type: set
            inner: html_page_anchor
            set_type: Domain\Entity\HtmlPage\Anchor
        themeColour:
            type: colour
            nullable: true
        title:
            type: string
        android:
            type: url
            nullable: true
        ios:
            type: url
            nullable: true
        isJournal:
            type: bool
