Domain\Entity\HttpResource:
    type: aggregate
    labels: [Web, Resource]
    identity:
        property: identity
        type: AppBundle\Entity\HttpResource\Identity
    properties:
        path:
            type: http_resource_path
        query:
            type: http_resource_query
        languages:
            type: set
            inner: language
            set_type: Domain\Model\Language
        charset:
            type: http_resource_charset

Domain\Entity\HostResource:
    type: relationship
    rel_type: RESOURCE_OF_HOST
    identity:
        property: identity
        type: AppBundle\Entity\HostResource\Identity
    startNode:
        property: resource
        type: AppBundle\Entity\HttpResource\Identity
        target: identity
    endNode:
        property: host
        type: AppBundle\Entity\Host\Identity
        target: identity
    properties:
        foundAt:
            type: point_in_time

Domain\Entity\ResourceAuthor:
    type: relationship
    rel_type: AUTHOR_OF_RESOURCE
    identity:
        property: identity
        type: AppBundle\Entity\ResourceAuthor\Identity
    startNode:
        property: author
        type: AppBundle\Entity\Author\Identity
        target: identity
    endNode:
        property: resource
        type: AppBundle\Entity\HttpResource\Identity
        target: identity
    properties:
        asOf:
            type: point_in_time

Domain\Entity\Alternate:
    type: relationship
    rel_type: ALTERNATE_OF_RESOURCE
    identity:
        property: identity
        type: AppBundle\Entity\Alternate\Identity
    startNode:
        property: alternate
        type: AppBundle\Entity\HttpResource\Identity
        target: identity
    endNode:
        property: resource
        type: AppBundle\Entity\HttpResource\Identity
        target: identity
    properties:
        language:
            type: language

Domain\Entity\Canonical:
    type: relationship
    rel_type: CANONICAL_OF_RESOURCE
    identity:
        property: identity
        type: AppBundle\Entity\Canonical\Identity
    startNode:
        property: canonical
        type: AppBundle\Entity\HttpResource\Identity
        target: identity
    endNode:
        property: resource
        type: AppBundle\Entity\HttpResource\Identity
        target: identity
    properties:
        foundAt:
            type: point_in_time
