Domain\Entity\HttpResource:
    type: aggregate
    labels: [Web, Resource]
    identity:
        property: identity
        type: AppBundle\Entity\HttpResource\Identity
    properties:
        path:
            type: http_resource_path
        query:
            type: http_resource_query
        languages:
            type: set
            inner: language
            set_type: Domain\Model\Language
        charset:
            type: http_resource_charset

Domain\Entity\HostResource:
    type: relationship
    rel_type: RESOURCE_OF_HOST
    identity:
        property: identity
        type: AppBundle\Entity\HostResource\Identity
    startNode:
        property: resource
        type: AppBundle\Entity\HttpResource\Identity
        target: identity
    endNode:
        property: host
        type: AppBundle\Entity\Host\Identity
        target: identity
    properties:
        foundAt:
            type: point_in_time
