web:
    resources:
        author:
            identity: identity
            gateway: author
            properties:
                identity:
                    type: string
                    access: [READ]
                name:
                    type: string
                    access: [READ, CREATE]
            options:
                actions: [get, create, options]

        citation:
            identity: identity
            gateway: citation
            properties:
                identity:
                    type: string
                    access: [READ]
                text:
                    type: string
                    access: [READ, CREATE]
            options:
                actions: [get, create, options]

        domain:
            identity: identity
            gateway: domain
            properties:
                identity:
                    type: string
                    access: [READ]
                authority:
                    type: string
                    access: [CREATE]
                name:
                    type: string
                    access: [READ]
                tld:
                    type: string
                    access: [READ]
                    variants: [top_level_domain]
            options:
                actions: [get, create, options]
