web:
    resources:
        author:
            identity: identity
            gateway: author
            properties:
                identity:
                    type: string
                    access: [READ]
                name:
                    type: string
                    access: [READ, CREATE]
            options:
                actions: [get, create, options]

        citation:
            identity: identity
            gateway: citation
            properties:
                identity:
                    type: string
                    access: [READ]
                text:
                    type: string
                    access: [READ, CREATE]
            options:
                actions: [get, create, options]

        domain:
            identity: identity
            gateway: domain
            properties:
                identity:
                    type: string
                    access: [READ]
                authority:
                    type: string
                    access: [CREATE]
                name:
                    type: string
                    access: [READ]
                tld:
                    type: string
                    access: [READ]
                    variants: [top_level_domain]
            options:
                actions: [get, create, options]

        resource:
            identity: identity
            gateway: http_resource
            properties:
                identity:
                    type: string
                    access: [READ]
                host:
                    type: string
                    access: [CREATE]
                path:
                    type: string
                    access: [READ, CREATE]
                query:
                    type: string
                    access: [READ, CREATE]
                languages:
                    type: set
                    access: [READ, CREATE]
                    options:
                        inner: string
                    optional: true
                charset:
                    type: string
                    access: [READ, CREATE]
                    optional: true

        image:
            identity: identity
            gateway: image
            properties:
                identity:
                    type: string
                    access: [READ]
                host:
                    type: string
                    access: [CREATE]
                path:
                    type: string
                    access: [READ, CREATE]
                query:
                    type: string
                    access: [READ, CREATE]
                descriptions:
                    type: set
                    access: [READ, CREATE]
                    optional: true
                    options:
                        inner: string
                dimension:
                    type: map
                    access: [READ, CREATE]
                    optional: true
                    options:
                        key: string
                        inner: int
                weight:
                    type: int
                    access: [READ, CREATE]
                    optional: true
