services:
    gateway.author:
        class: AppBundle\Rest\Gateway\AuthorGateway
        arguments:
            - '@gateway.author.creator'
            - '@gateway.author.accessor'
        tags:
            - { name: innmind_rest_server.gateway, alias: author }

    gateway.author.creator:
        class: AppBundle\Rest\Gateway\AuthorGateway\ResourceCreator
        arguments:
            - '@command_bus'

    gateway.author.accessor:
        class: AppBundle\Rest\Gateway\AuthorGateway\ResourceAccessor
        arguments:
            - '@repository.author'
