services:
    handler.register_author:
        class: Domain\Handler\RegisterAuthorHandler
        arguments:
            - '@repository.author'
        tags:
            - { name: innmind_command_bus.handler, handles: Domain\Command\RegisterAuthor }

    handler.register_citation:
        class: Domain\Handler\RegisterCitationHandler
        arguments:
            - '@repository.citation'
        tags:
            - { name: innmind_command_bus.handler, handles: Domain\Command\RegisterCitation }

    handler.register_domain:
        class: Domain\Handler\RegisterDomainHandler
        arguments:
            - '@repository.domain'
            - '@domain_parser'
        tags:
            - { name: innmind_command_bus.handler, handles: Domain\Command\RegisterDomain }

    handler.register_host:
        class: Domain\Handler\RegisterHostHandler
        arguments:
            - '@repository.host'
            - '@repository.domain_host'
            - '@clock'
        tags:
            - { name: innmind_command_bus.handler, handles: Domain\Command\RegisterHost }
