services:
    handler.register_author:
        class: Domain\Handler\RegisterAuthorHandler
        arguments:
            - '@repository.author'
        tags:
            - { name: innmind_command_bus.handler, handles: Domain\Command\RegisterAuthor }

    handler.register_citation:
        class: Domain\Handler\RegisterCitationHandler
        arguments:
            - '@repository.citation'
        tags:
            - { name: innmind_command_bus.handler, handles: Domain\Command\RegisterCitation }
