services:
    handler.register_author:
        class: Domain\Handler\RegisterAuthorHandler
        arguments:
            - '@repository.author'
        tags:
            - { name: innmind_command_bus.handler, handles: Domain\Command\RegisterAuthor }

    handler.register_citation:
        class: Domain\Handler\RegisterCitationHandler
        arguments:
            - '@repository.citation'
        tags:
            - { name: innmind_command_bus.handler, handles: Domain\Command\RegisterCitation }

    handler.register_domain:
        class: Domain\Handler\RegisterDomainHandler
        arguments:
            - '@repository.domain'
            - '@domain_parser'
        tags:
            - { name: innmind_command_bus.handler, handles: Domain\Command\RegisterDomain }

    handler.register_host:
        class: Domain\Handler\RegisterHostHandler
        arguments:
            - '@repository.host'
            - '@repository.domain_host'
            - '@clock'
        tags:
            - { name: innmind_command_bus.handler, handles: Domain\Command\RegisterHost }

    handler.register_http_resource:
        class: Domain\Handler\RegisterHttpResourceHandler
        arguments:
            - '@repository.http_resource'
            - '@repository.host_resource'
            - '@clock'
        tags:
            - { name: innmind_command_bus.handler, handles: Domain\Command\RegisterHttpResource }

    handler.http_resource.specify_charset:
        class: Domain\Handler\HttpResource\SpecifyCharsetHandler
        arguments:
            - '@repository.http_resource'
        tags:
            - { name: innmind_command_bus.handler, handles: Domain\Command\HttpResource\SpecifyCharset }

    handler.http_resource.specify_languages:
        class: Domain\Handler\HttpResource\SpecifyLanguagesHandler
        arguments:
            - '@repository.http_resource'
        tags:
            - { name: innmind_command_bus.handler, handles: Domain\Command\HttpResource\SpecifyLanguages }

    handler.register_image:
        class: Domain\Handler\RegisterImageHandler
        arguments:
            - '@repository.image'
            - '@repository.host_resource'
            - '@clock'
        tags:
            - { name: innmind_command_bus.handler, handles: Domain\Command\RegisterImage }

    handler.image.specify_dimension:
        class: Domain\Handler\Image\SpecifyDimensionHandler
        arguments:
            - '@repository.image'
        tags:
            - { name: innmind_command_bus.handler, handles: Domain\Command\Image\SpecifyDimension }

    handler.image.specify_weight:
        class: Domain\Handler\Image\SpecifyWeightHandler
        arguments:
            - '@repository.image'
        tags:
            - { name: innmind_command_bus.handler, handles: Domain\Command\Image\SpecifyWeight }

    handler.image.add_description:
        class: Domain\Handler\Image\AddDescriptionHandler
        arguments:
            - '@repository.image'
        tags:
            - { name: innmind_command_bus.handler, handles: Domain\Command\Image\AddDescription }
