services:
    listener.exception:
        class: AppBundle\EventListener\ExceptionListener
        arguments:
            -
                Domain\Exception\AlternateAlreadyExistException: Innmind\Http\Exception\Http\Conflict
                Domain\Exception\AuthorAlreadyExistException: Innmind\Http\Exception\Http\Conflict
                Domain\Exception\CanonicalAlreadyExistException: Innmind\Http\Exception\Http\Conflict
                Domain\Exception\CitationAlreadyExistException: Innmind\Http\Exception\Http\Conflict
                Domain\Exception\CitationAppearanceAlreadyExistException: Innmind\Http\Exception\Http\Conflict
                Domain\Exception\DomainAlreadyExistException: Innmind\Http\Exception\Http\Conflict
                Domain\Exception\HostAlreadyExistException: Innmind\Http\Exception\Http\Conflict
                Domain\Exception\HtmlPageAlreadyExistException: Innmind\Http\Exception\Http\Conflict
                Domain\Exception\HttpResourceAlreadyExistException: Innmind\Http\Exception\Http\Conflict
                Domain\Exception\ImageAlreadyExistException: Innmind\Http\Exception\Http\Conflict
                Domain\Exception\ReferenceAlreadyExistException: Innmind\Http\Exception\Http\Conflict
                Domain\Exception\AlternateNotFoundException: Innmind\Http\Exception\Http\NotFound
                Domain\Exception\AuthorNotFoundException: Innmind\Http\Exception\Http\NotFound
                Domain\Exception\CanonicalNotFoundException: Innmind\Http\Exception\Http\NotFound
                Domain\Exception\CitationNotFoundException: Innmind\Http\Exception\Http\NotFound
                Domain\Exception\CitationAppearanceNotFoundException: Innmind\Http\Exception\Http\NotFound
                Domain\Exception\DomainNotFoundException: Innmind\Http\Exception\Http\NotFound
                Domain\Exception\HostNotFoundException: Innmind\Http\Exception\Http\NotFound
                Domain\Exception\HtmlPageNotFoundException: Innmind\Http\Exception\Http\NotFound
                Domain\Exception\HttpResourceNotFoundException: Innmind\Http\Exception\Http\NotFound
                Domain\Exception\ImageNotFoundException: Innmind\Http\Exception\Http\NotFound
                Domain\Exception\ReferenceNotFoundException: Innmind\Http\Exception\Http\NotFound
        factory:
            - AppBundle\Factory\ExceptionListenerFactory
            - make
        tags:
            - { name: kernel.event_subscriber }

    event.listener.store_domain_event:
        class: AppBundle\Listener\StoreDomainEventListener
        arguments:
            - '@innmind_filesystem'
        tags:
            - { name: innmind_event_bus.listener, listen_to: Domain\Event\* }
