services:
    listener.exception:
        class: AppBundle\EventListener\ExceptionListener
        arguments:
            -
                Domain\Exception\AlternateAlreadyExist: Innmind\Http\Exception\Http\Conflict
                Domain\Exception\AuthorAlreadyExist: Innmind\Http\Exception\Http\Conflict
                Domain\Exception\CanonicalAlreadyExist: Innmind\Http\Exception\Http\Conflict
                Domain\Exception\CitationAlreadyExist: Innmind\Http\Exception\Http\Conflict
                Domain\Exception\CitationAppearanceAlreadyExist: Innmind\Http\Exception\Http\Conflict
                Domain\Exception\DomainAlreadyExist: Innmind\Http\Exception\Http\Conflict
                Domain\Exception\HostAlreadyExist: Innmind\Http\Exception\Http\Conflict
                Domain\Exception\HtmlPageAlreadyExist: Innmind\Http\Exception\Http\Conflict
                Domain\Exception\HttpResourceAlreadyExist: Innmind\Http\Exception\Http\Conflict
                Domain\Exception\ImageAlreadyExist: Innmind\Http\Exception\Http\Conflict
                Domain\Exception\ReferenceAlreadyExist: Innmind\Http\Exception\Http\Conflict
                Domain\Exception\AlternateNotFound: Innmind\Http\Exception\Http\NotFound
                Domain\Exception\AuthorNotFound: Innmind\Http\Exception\Http\NotFound
                Domain\Exception\CanonicalNotFound: Innmind\Http\Exception\Http\NotFound
                Domain\Exception\CitationNotFound: Innmind\Http\Exception\Http\NotFound
                Domain\Exception\CitationAppearanceNotFound: Innmind\Http\Exception\Http\NotFound
                Domain\Exception\DomainNotFound: Innmind\Http\Exception\Http\NotFound
                Domain\Exception\HostNotFound: Innmind\Http\Exception\Http\NotFound
                Domain\Exception\HtmlPageNotFound: Innmind\Http\Exception\Http\NotFound
                Domain\Exception\HttpResourceNotFound: Innmind\Http\Exception\Http\NotFound
                Domain\Exception\ImageNotFound: Innmind\Http\Exception\Http\NotFound
                Domain\Exception\ReferenceNotFound: Innmind\Http\Exception\Http\NotFound
        factory:
            - AppBundle\Factory\ExceptionListenerFactory
            - make
        tags:
            - { name: kernel.event_subscriber }

    event.listener.store_domain_event:
        class: AppBundle\Listener\StoreDomainEventListener
        arguments:
            - '@innmind_filesystem'
        tags:
            - { name: innmind_event_bus.listener, listen_to: Domain\Event\* }
