services:
    repository.author:
        class: AppBundle\Repository\Neo4j\AuthorRepository
        arguments:
            - '@repository.neo4j.author'

    repository.neo4j.author:
        factory:
            - '@innmind_neo4j.manager'
            - 'repository'
        arguments:
            - Domain\Entity\Author

    repository.resource_author:
        class: AppBundle\Repository\Neo4j\ResourceAuthorRepository
        arguments:
            - '@repository.neo4j.resource_author'

    repository.neo4j.resource_author:
        factory:
            - '@innmind_neo4j.manager'
            - 'repository'
        arguments:
            - Domain\Entity\ResourceAuthor

    repository.citation:
        class: AppBundle\Repository\Neo4j\CitationRepository
        arguments:
            - '@repository.neo4j.citation'

    repository.neo4j.citation:
        factory:
            - '@innmind_neo4j.manager'
            - 'repository'
        arguments:
            - Domain\Entity\Citation

    repository.citation_appearance:
        class: AppBundle\Repository\Neo4j\CitationAppearanceRepository
        arguments:
            - '@repository.neo4j.citation_appearance'

    repository.neo4j.citation_appearance:
        factory:
            - '@innmind_neo4j.manager'
            - 'repository'
        arguments:
            - Domain\Entity\CitationAppearance

    repository.domain:
        class: AppBundle\Repository\Neo4j\DomainRepository
        arguments:
            - '@repository.neo4j.domain'

    repository.neo4j.domain:
        factory:
            - '@innmind_neo4j.manager'
            - 'repository'
        arguments:
            - Domain\Entity\Domain

    repository.domain_host:
        class: AppBundle\Repository\Neo4j\DomainHostRepository
        arguments:
            - '@repository.neo4j.domain_host'

    repository.neo4j.domain_host:
        factory:
            - '@innmind_neo4j.manager'
            - 'repository'
        arguments:
            - Domain\Entity\DomainHost

    repository.host:
        class: AppBundle\Repository\Neo4j\HostRepository
        arguments:
            - '@repository.neo4j.host'

    repository.neo4j.host:
        factory:
            - '@innmind_neo4j.manager'
            - 'repository'
        arguments:
            - Domain\Entity\Host

    repository.host_resource:
        class: AppBundle\Repository\Neo4j\HostResourceRepository
        arguments:
            - '@repository.neo4j.host_resource'

    repository.neo4j.host_resource:
        factory:
            - '@innmind_neo4j.manager'
            - 'repository'
        arguments:
            - Domain\Entity\HostResource

    repository.http_resource:
        class: AppBundle\Repository\Neo4j\HttpResourceRepository
        arguments:
            - '@repository.neo4j.http_resource'

    repository.neo4j.http_resource:
        factory:
            - '@innmind_neo4j.manager'
            - 'repository'
        arguments:
            - Domain\Entity\HttpResource

    repository.image:
        class: AppBundle\Repository\Neo4j\ImageRepository
        arguments:
            - '@repository.neo4j.image'

    repository.neo4j.image:
        factory:
            - '@innmind_neo4j.manager'
            - 'repository'
        arguments:
            - Domain\Entity\Image

    repository.html_page:
        class: AppBundle\Repository\Neo4j\HtmlPageRepository
        arguments:
            - '@repository.neo4j.html_page'

    repository.neo4j.html_page:
        factory:
            - '@innmind_neo4j.manager'
            - 'repository'
        arguments:
            - Domain\Entity\HtmlPage

    repository.alternate:
        class: AppBundle\Repository\Neo4j\AlternateRepository
        arguments:
            - '@repository.neo4j.alternate'

    repository.neo4j.alternate:
        factory:
            - '@innmind_neo4j.manager'
            - 'repository'
        arguments:
            - Domain\Entity\Alternate

    repository.canonical:
        class: AppBundle\Repository\Neo4j\CanonicalRepository
        arguments:
            - '@repository.neo4j.canonical'

    repository.neo4j.canonical:
        factory:
            - '@innmind_neo4j.manager'
            - 'repository'
        arguments:
            - Domain\Entity\Canonical
