services:
    repository.author:
        class: AppBundle\Repository\Neo4j\AuthorRepository
        arguments:
            - '@repository.neo4j.author'

    repository.neo4j.author:
        factory:
            - '@innmind_neo4j.manager'
            - 'repository'
        arguments:
            - Domain\Entity\Author

    repository.citation:
        class: AppBundle\Repository\Neo4j\CitationRepository
        arguments:
            - '@repository.neo4j.citation'

    repository.neo4j.citation:
        factory:
            - '@innmind_neo4j.manager'
            - 'repository'
        arguments:
            - Domain\Entity\Citation

    repository.domain:
        class: AppBundle\Repository\Neo4j\DomainRepository
        arguments:
            - '@repository.neo4j.domain'

    repository.neo4j.domain:
        factory:
            - '@innmind_neo4j.manager'
            - 'repository'
        arguments:
            - Domain\Entity\Domain

    repository.host:
        class: AppBundle\Repository\Neo4j\HostRepository
        arguments:
            - '@repository.neo4j.host'

    repository.neo4j.host:
        factory:
            - '@innmind_neo4j.manager'
            - 'repository'
        arguments:
            - Domain\Entity\Host

    repository.http_resource:
        class: AppBundle\Repository\Neo4j\HttpResourceRepository
        arguments:
            - '@repository.neo4j.http_resource'

    repository.neo4j.http_resource:
        factory:
            - '@innmind_neo4j.manager'
            - 'repository'
        arguments:
            - Domain\Entity\HttpResource

    repository.image:
        class: AppBundle\Repository\Neo4j\ImageRepository
        arguments:
            - '@repository.neo4j.image'

    repository.neo4j.image:
        factory:
            - '@innmind_neo4j.manager'
            - 'repository'
        arguments:
            - Domain\Entity\Image
